name = "UnitAliases"
uuid = "96ae54c0-0dff-11e9-11b2-27e67f6cc5ea"
authors = ["Cody Greer <codyjgreer@gmail.com>"]
version = "0.1.1"

[deps]
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
Unitful = ">=0.8.0, <0.8.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
